config/routes.rb
Rails.application.routes.draw do

  post 'bartender/:select_drink' => 'bartender#select_drink'

  get 'bartender/:select_drink' => 'bartender#select_drink'

  post '/select_drink' => 'bartender#select_drink'

  get '/select_drink' => 'bartender#select_drink'

  post 'bartender/:notfound' => 'bartender#notfound'

  get 'bartender/:notfound' => 'bartender#notfound'

  post '/notfound' => 'bartender#notfound'

  get '/notfound' => 'bartender#notfound'

  resources :drink_ingredients

  resources :ingredients

  resources :drinks

  root 'bartender#index', as: 'bartender'

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_format_of :name, without: /\d/

  has_many :drink_ingredients
  has_many :ingredients, :through => :drink_ingredients

  def to_param
    name
  end

  #def self.find(name)
   # find_by_name(name)
  #end
end

app/models/drink_ingredient.rb
class DrinkIngredient < ActiveRecord::Base
  belongs_to :drink
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :drink_ingredients
  has_many :drinks, :through => :drink_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bartender_controller.rb
class BartenderController < ApplicationController
  def index
  end

  def select_drink
    @x = params[:method]
    @y = params[:name]
    @selection = Drink.joins(:ingredients).where(method: @x, ingredients: {name: @y})
    unless @selection.empty?
      target = @selection.shuffle[0]
      redirect_to drink_path(target, :method => @x, :name => @y)
      # redirect_to target
    else
      render :notfound
    end
  end

end

app/controllers/drink_ingredients_controller.rb
class DrinkIngredientsController < ApplicationController
  before_action :set_drink_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /drink_ingredients
  # GET /drink_ingredients.json
  def index
    @drink_ingredients = DrinkIngredient.all
  end

  # GET /drink_ingredients/1
  # GET /drink_ingredients/1.json
  def show
  end

  # GET /drink_ingredients/new
  def new
    @drink_ingredient = DrinkIngredient.new
  end

  # GET /drink_ingredients/1/edit
  def edit
  end

  # POST /drink_ingredients
  # POST /drink_ingredients.json
  def create
    @drink_ingredient = DrinkIngredient.new(drink_ingredient_params)

    respond_to do |format|
      if @drink_ingredient.save
        format.html { redirect_to @drink_ingredient, notice: 'Drink ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @drink_ingredient }
      else
        format.html { render :new }
        format.json { render json: @drink_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drink_ingredients/1
  # PATCH/PUT /drink_ingredients/1.json
  def update
    respond_to do |format|
      if @drink_ingredient.update(drink_ingredient_params)
        format.html { redirect_to @drink_ingredient, notice: 'Drink ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @drink_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drink_ingredients/1
  # DELETE /drink_ingredients/1.json
  def destroy
    @drink_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to drink_ingredients_url, notice: 'Drink ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink_ingredient
      @drink_ingredient = DrinkIngredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_ingredient_params
      params.require(:drink_ingredient).permit(:float)
    end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
    @drink = Drink.find_by_name(params[:id])
    if params[:method] && params[:name]
      @button = true
    else
      @button = false
    end
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find_by_name(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:name, :method, :glass, :garnish, :ice, :notes)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bartender_helper.rb
module BartenderHelper
end

app/helpers/drink_ingredients_helper.rb
module DrinkIngredientsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/bartender/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Boozapp-It's a Booze App</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

  <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/drinks"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/drinks">Drinks</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                  <div class="intro-text">
                        <span class="name">Boozapp</span>
                        <hr />
                        <span class="skills">It's a Booze App</span>
                    </div>
                </div>
            </div>
        </div>
    </header>



<div class="col-lg-12 text-center">
<h1>What are you drinking?</h1>

<%= form_tag("select_drink") do %>
  <p>
     <p>
      <select name="name">
        <% Ingredient.joins(:drinks).where("drink_ingredients.role = ?", "Base").select(:name).distinct.each do |i| %>
          <option value="<%= i.name %>"><%= i.name %></option>
        <% end %>
    </select>
    
    <h2>Shaken or stirred?</h2>
    <select name="method">
        <% Drink.uniq.pluck(:method).each do |m| %>
          <option value="<%= m %>"><%= m %></option>
        <% end %>
    </select>
    
  <%= submit_tag "Search" %>
  </p>
<% end %>
</div>
</body>

app/views/bartender/notfound.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Boozapp-It's a Booze App</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

  <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/drinks"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/drinks">Drinks</a>
                    </li>
                    <li class="page-scroll">
                        <a href="/">Back to the Bar</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                  <div class="intro-text">
                        <span class="name">That is not a real thing.</span>
                        <hr />
                        <span class="skills">I'm a bartender, not a miracle worker.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>



<div class="col-lg-12 text-center">
<h1>Maybe you'd like to try<a class="bold-link" href="/drinks"> something else?</a></h1>

</div>
</body>

app/views/bartender/select_drink.html.erb
<%= @selection %>

app/views/drink_ingredients/_form.html.erb
<%= form_for(@drink_ingredient) do |f| %>
  <% if @drink_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink_ingredient.errors.count, "error") %> prohibited this drink_ingredient from being saved:</h2>

      <ul>
      <% @drink_ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :float %><br>
    <%= f.text_field :float %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drink_ingredients/edit.html.erb
<h1>Editing drink_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink_ingredient %> |
<%= link_to 'Back', drink_ingredients_path %>

app/views/drink_ingredients/index.html.erb
<h1>Listing drink_ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Float</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drink_ingredients.each do |drink_ingredient| %>
      <tr>
        <td><%= drink_ingredient.measure %></td>
        <td><%= link_to 'Recipe', drink_ingredient %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drink ingredient', new_drink_ingredient_path %>

app/views/drink_ingredients/new.html.erb
<h1>New drink_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', drink_ingredients_path %>

app/views/drink_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Float:</strong>
  <%= @drink_ingredient.float %>
</p>

<%= link_to 'Back', drink_ingredients_path %>

app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :method %><br>
    <%= f.text_field :method %>
  </div>
  <div class="field">
    <%= f.label :glass %><br>
    <%= f.text_field :glass %>
  </div>
  <div class="field">
    <%= f.label :garnish %><br>
    <%= f.text_field :garnish %>
  </div>
  <div class="field">
    <%= f.label :ice %><br>
    <%= f.text_field :ice %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Boozapp-It's a Booze App</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

  <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/drinks"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/">Back to the Bar</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                  <div class="intro-text">
                        <span class="name">The Drink List</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

 

<% form_tag drinks_path do %>
  <p>
    <%= text_field_tag :search %>
    <%= submit_tag "Search" %>
  </p>

<% end %>

<section class= id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Method</th>
      <th>Glass</th>
      <th>Garnish</th>
      <th>Ice</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinks.each do |drink| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= drink.name %></td>
        <td><%= drink.method %></td>
        <td><%= drink.glass %></td>
        <td><%= drink.garnish %></td>
        <td><%= drink.ice %></td>
        <td><%= drink.notes %></td>
        <td><%= link_to 'Recipe', drink %></td>
      </tr>
    <% end %>
  </tbody>
</table>
            </div>
        </div>
    </section>

<br>

<%= link_to 'New Drink', new_drink_path %>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.description %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ingredient.description %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boozapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>